#!/bin/bash -x

#PBS -l mem=105g
#PBS -l vmem=115g
#PBS -l walltime=23:59:00
#PBS -l nodes=1:ppn=31
#PBS -o /hpf/largeprojects/struglis/datasets/uk_biobank_40946/imputation/bplink/job_output
#PBS -e /hpf/largeprojects/struglis/datasets/uk_biobank_40946/imputation/bplink/job_output
#PBS -d /hpf/largeprojects/struglis/datasets/uk_biobank_40946/imputation
#PBS -N bgen_to_plink

hostname
date

export PATH=$PATH:$PBS_O_WORKDIR

echo "Working dir is ${PBS_O_WORKDIR}"
cd $PBS_O_WORKDIR

chr=$PBS_ARRAYID
if [ $PBS_ARRAYID = "23" ]; then chr="X"; fi

module load plink/2.0
plink2 --bgen ukb_imp_chr${chr}_v3.bgen --make-bed --memory 100000 --sample sample_files/ukb40946_imp_chr${chr}_v3_s487296.sample --out bplink/ukb_imp_chr${chr}_v3 --threads 30

echo "Done"
